name: Build Image

on: push

jobs:    
    build:      
      name: Build 
      runs-on: ubuntu-latest
      steps:        
        - uses: actions/checkout@v2                           
        - name: current dir
          run: pwd
        - name: list files                                      
          run: chmod 777 build.ps1
        - name: list files                                      
          run: ls -la        
        - name: docker build                                      
          run: docker build -t owlvey-archon:latest .
        - name: docker login
          run: docker login -u="${{ secrets.DOCKER_USERNAME }}" -p="${{ secrets.DOCKER_PASSWORD }}"
        - name: docker tag
          run: |
            docker tag grafana-owlvey owlvey/archon:latest
            docker tag grafana-owlvey owlvey/archon:${{ github.sha }}                  
            docker push owlvey/archon